/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"JetBrains Mono Variable"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
        display: ['"JetBrains Mono Variable"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
        mono: ['"JetBrains Mono Variable"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    logs: false,
    themes: [
      {
        'homealias-dark': {
          'color-scheme': 'dark',
          primary: '#3b5bdb',
          'primary-content': '#ffffff',
          secondary: '#4da3ff',
          'secondary-content': '#05070d',
          accent: '#8dc7ff',
          'accent-content': '#05070d',
          neutral: '#151d2b',
          'neutral-content': '#a9b6d6',
          'base-100': '#0d121c',
          'base-200': '#05070d',
          'base-300': '#2a3140',
          'base-content': '#eaf0ff',
          info: '#4da3ff',
          'info-content': '#05070d',
          success: '#2bc08a',
          'success-content': '#03140d',
          warning: '#ffb020',
          'warning-content': '#271a00',
          error: '#ff5c7a',
          'error-content': '#2a0509',
          '--rounded-box': '0.375rem',
          '--rounded-btn': '0.25rem',
          '--rounded-badge': '0.25rem',
          '--animation-btn': '0.15s',
          '--animation-input': '0.15s',
          '--btn-focus-scale': '1',
          '--border-btn': '1px',
          '--tab-border': '2px',
          '--tab-radius': '0.25rem',
        },
      },
      {
        'homealias-light': {
          'color-scheme': 'light',
          primary: '#2447d6',
          'primary-content': '#ffffff',
          secondary: '#1f6fd1',
          'secondary-content': '#ffffff',
          accent: '#3b5bdb',
          'accent-content': '#ffffff',
          neutral: '#0d121c',
          'neutral-content': '#d5dcef',
          'base-100': '#ffffff',
          'base-200': '#f1f4fb',
          'base-300': '#d5dceb',
          'base-content': '#0d121c',
          info: '#1f6fd1',
          'info-content': '#ffffff',
          success: '#0c7a4c',
          'success-content': '#ffffff',
          warning: '#a86500',
          'warning-content': '#ffffff',
          error: '#c4283c',
          'error-content': '#ffffff',
          '--rounded-box': '0.375rem',
          '--rounded-btn': '0.25rem',
          '--rounded-badge': '0.25rem',
          '--animation-btn': '0.15s',
          '--animation-input': '0.15s',
          '--btn-focus-scale': '1',
          '--border-btn': '1px',
          '--tab-border': '2px',
          '--tab-radius': '0.25rem',
        },
      },
    ],
    darkTheme: 'homealias-dark',
  },
}
